### ISSUE TITLE
Ungewöhnlich große Treffermenge

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#43]
Bei der Suche über alle Felder nach der Zeitschriften Signatur 04z3 liefert ES 996 Treffer. Das Produktionssystem liefert genau einen Treffer. Warum kommen bei der sehr spezifischen Anfrage so viele Treffer?

**Comment by msievers** [comment]
Der aktuelle default Analyzer

```yaml
---
analysis:
  filter:
    ubpb_pattern_replace_ß:
      pattern: "ß"
      type: "pattern_replace"
      replacement: "ss"
    ubpb_pattern_replace_ö:
      pattern: "ö"
      type: "pattern_replace"
      replacement: "oe"
    ubpb_word_delimiter:
      type: "word_delimiter"
      type_table:
      - "+ => ALPHA"
      - "# => ALPHA"
      - ". => ALPHA"
    ubpb_stop:
      type: "stop"
      stopwords:
      - "_english_"
      - "_german_"
    ubpb_pattern_replace_ä:
      pattern: "ä"
      type: "pattern_replace"
      replacement: "ae"
    ubpb_pattern_replace_ü:
      pattern: "ü"
      type: "pattern_replace"
      replacement: "ue"
  analyzer:
    default:
      filter:
      - "standard"
      - "lowercase"
      - "ubpb_pattern_replace_ä"
      - "ubpb_pattern_replace_ö"
      - "ubpb_pattern_replace_ü"
      - "ubpb_pattern_replace_ß"
      - "ubpb_word_delimiter"
      - "ubpb_stop"
      type: "custom"
      tokenizer: "whitespace"
```

benutzt `ubpb_word_delemiter` welcher Worte an bestimmte Grenzen aufteilt. Eine diese Grenzen ist die Buchstaben-Zahlen-Grenze. D.h. konkret sucht er momentan bei der Eingabe "04z3" nach "04" "z" "3".

**Comment by msievers** [comment]
Eine Lösung wäre die Konfiguration mit Hilfe des Parameters `split_on_numerics: false`anzupassen.

```yaml
ubpb_word_delimiter:
  type: "word_delimiter"
  split_on_numerics: false
  type_table:
  - "+ => ALPHA"
  - "# => ALPHA"
  - ". => ALPHA"
```
