### ISSUE TITLE
"Manuelles" Boosting

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#89]
Es gibt hin und wieder den Wunsch, bestimmte Titel besonders hoch zu ranken. Dies können z.B. Zeitungen sein, besondere E-Books o.ä.

Wir haben mit ES die Möglichkeit dies über verschiedene Arten zu realisieren. Wichtig dabei ist die Möglichkeit das Boosting unabhängig von der gestellten Anfrage durchführen zu können.

Einen Überblick über Möglichkeiten listet der folgende Link auf: http://stackoverflow.com/questions/12427449/elasticsearch-boosting-relevance-based-on-field-value

Eine Alternative ist die übrigen Treffer mit einem negativen Boost-Faktor zu belegen:

```
POST http://ubstage1:9200/katalog/_search?format=json

---
size: 20
query:
  boosting:
      positive:
        bool:
          must:
            - simple_query_string: 
                query: "süddeutsche zeitung"
                fields: 
                  - "title_search"
                default_operator: "and"
      negative:
        bool:
          must_not:
            - term:
                erscheinungsform_facet: newspaper

      negative_boost: 0.2
```

Es bleibt zu klären wie dieses technische Mittel in der Praxis sinnvoll für welche Arten von Titeln eingesetzt werden kann/soll.
